---
- name: SCRIPT FOR BACKUP
  gather_facts: false
  hosts: ASBR2
  vars_files:
    - /home/coder/creds_junos
  tasks:
   - name: BACKUP RUNNING-CONFIG
     junipernetworks.junos.junos_config:
       backup: yes
       backup_options:
         dir_path: /home/coder/backup
         backup_format: json
         filename: ASBR2.conf


     

